"""Private media transport. Filenames and IDs are generated by the server."""
import math
from cloud.client import CloudError, ident

MAX_BYTES = 20_000_000
CHUNK_BYTES = 5_000_000
BUCKET = 'originals'


class Files:
    def __init__(self, client):
        self.client = client

    def path(self, file_id):
        return f'/storage/buckets/{BUCKET}/files/{ident(file_id)}'

    def metadata(self, file_id):
        row = self.client.request('GET', self.path(file_id))
        self.client.private(row)
        if row.get('$id') != file_id:
            raise CloudError()
        return row

    def chunk(self, file_id, name, data, offset, size):
        if not 0 < len(data) <= CHUNK_BYTES or not 0 < size <= MAX_BYTES or offset % CHUNK_BYTES:
            raise ValueError('Invalid upload chunk.')
        if len(data) != min(CHUNK_BYTES, size - offset):
            raise ValueError('Invalid upload chunk length.')
        headers = {'Content-Range': f'bytes {offset}-{offset + len(data) - 1}/{size}'}
        if offset:
            headers['X-Appwrite-ID'] = file_id
        row = self.client.request('POST', f'/storage/buckets/{BUCKET}/files',
            data={'fileId': file_id}, headers=headers,
            files={'file': (name, data, 'application/octet-stream')})
        self.client.private(row)
        if row.get('$id') != file_id or row.get('chunksUploaded') != offset // CHUNK_BYTES + 1:
            raise CloudError()
        return row

    def complete(self, row, size):
        return (row.get('sizeOriginal') == size and
                row.get('chunksTotal') == math.ceil(size / CHUNK_BYTES) and
                row.get('chunksUploaded') == row.get('chunksTotal'))

    def download(self, file_id):
        import httpx
        try:
            with self.client.http.stream('GET', self.path(file_id).lstrip('/') + '/download') as response:
                if response.status_code != 200:
                    raise CloudError(response.status_code)
                data = bytearray()
                for chunk in response.iter_bytes():
                    data.extend(chunk)
                    if len(data) > MAX_BYTES:
                        raise CloudError(413, 'file_too_large')
                return bytes(data)
        except httpx.HTTPError:
            raise CloudError() from None

    def delete(self, file_id):
        try:
            self.client.request('DELETE', self.path(file_id))
        except CloudError as exc:
            if exc.status != 404:
                raise
