import secrets
from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse

router = APIRouter()

@router.get('/account/{action}', response_class=HTMLResponse)
def account_page(action: str):
    if action not in ('reset-password', 'verify-email', 'delete'): raise HTTPException(404)
    if action == 'delete': return deletion_page()
    reset = action == 'reset-password'
    nonce = secrets.token_urlsafe(24)
    title = 'Reset your password' if reset else 'Verify your email'
    field = '<label>New password<input id="password" type="password" minlength="10" maxlength="128" required autocomplete="new-password"></label>' if reset else ''
    script = """const token=new URLSearchParams(location.hash.slice(1)).get('token');history.replaceState(null,'',location.pathname);const form=document.getElementById('form');form.onsubmit=async e=>{e.preventDefault();const button=document.getElementById('submit');button.disabled=true;try{const body={token};if(document.getElementById('password'))body.password=document.getElementById('password').value;const r=await fetch('/api/auth/ACTION',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();document.getElementById('status').textContent=r.ok?'Complete. Return to Ditto and sign in.':data.detail||'Try again later.';if(!r.ok)button.disabled=false;}catch(e){document.getElementById('status').textContent='Connection failed. Try again.';button.disabled=false;}};if(!token){document.getElementById('status').textContent='Link is missing. Request a new email from Ditto.';document.getElementById('submit').disabled=true;}""".replace('ACTION', action)
    page = '<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ditto account</title><style nonce="'+nonce+'">body{font:18px system-ui;background:#fff8f1;color:#353036;margin:0;padding:24px}main{max-width:440px;margin:8vh auto;padding:32px;background:#fff;border-radius:24px;border:1px solid #eed6cb}input,button{display:block;box-sizing:border-box;width:100%;padding:14px;margin-top:12px;border-radius:12px;border:1px solid #bda7a2}button{background:#f7ac9a;color:#353036;font-weight:600}a{color:#754544}</style></head><body><main><h1>ditto</h1><h2>'+title+'</h2><form id="form">'+field+'<button id="submit">Continue</button></form><p role="status" id="status"></p><a href="/privacy">Privacy</a></main><script nonce="'+nonce+'">'+script+'</script></body></html>'
    return HTMLResponse(page, headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; script-src 'nonce-"+nonce+"'; style-src 'nonce-"+nonce+"'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff'})


def deletion_page():
    nonce=secrets.token_urlsafe(24)
    script="""document.getElementById('form').onsubmit=async e=>{e.preventDefault();if(!document.getElementById('confirm').checked)return;const button=document.getElementById('submit');button.disabled=true;const email=document.getElementById('email').value,password=document.getElementById('password').value;try{const login=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const session=await login.json();if(!login.ok)throw new Error(session.detail||'Sign-in failed.');const result=await fetch('/api/auth/delete-account',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.token},body:JSON.stringify({password})});const data=await result.json();if(!result.ok)throw new Error(data.detail||'Deletion failed.');document.getElementById('form').remove();document.getElementById('status').textContent='Account deleted. Return to Ditto and log out. Existing sessions have been revoked.';}catch(error){document.getElementById('status').textContent=error.message;button.disabled=false;}document.getElementById('password')&&(document.getElementById('password').value='');};"""
    page='<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Delete Ditto account</title><style nonce="'+nonce+'">body{font:18px system-ui;background:#fff8f1;color:#353036;padding:24px}main{max-width:480px;margin:5vh auto}input,button{display:block;padding:12px;margin:12px 0}button{background:#f7ac9a;border-radius:12px}</style></head><body><main><h1>Delete your Ditto account</h1><p>This removes account records, cases, stored Instagram credentials and private media. Access is revoked immediately. Media cleanup may be queued if storage is unavailable. Backup copies age out under the operator?s retention policy. This does not delete your Instagram account or posts.</p><form id="form"><label>Email<input id="email" type="email" required autocomplete="username"></label><label>Password<input id="password" type="password" minlength="10" required autocomplete="current-password"></label><label><input id="confirm" type="checkbox" required>I understand deletion is permanent.</label><button id="submit">Delete account permanently</button></form><p id="status" role="status"></p><a href="/privacy">Privacy</a></main><script nonce="'+nonce+'">'+script+'</script></body></html>'
    return HTMLResponse(page,headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; script-src 'nonce-"+nonce+"'; style-src 'nonce-"+nonce+"'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'"})
